<?php
/**
 * @author Marco Bunge
 * @copyright 2012 Marco Bunge <efika@rubymatrix.de>
 */
?>
<ul class="nav nav-tabs nav-stacked">
    <?php foreach ($this->list as $item) : ?>
        <li>
            <a href="<?php echo $this->url('units/' . $this->controllerName . '/details', array('id' => $item->offsetGet('id'))) ?>"><?php echo $item->offsetGet('name') ?></a>
        </li>
    <?php endforeach; ?>
</ul>