<?php
/**
 * @author Marco Bunge
 * @copyright 2012 Marco Bunge <efika@rubymatrix.de>
 */

?>
<div class="hero-unit">
    <h1>Game Units</h1>
</div>
<div class="row">
    <div class="span12">
        <h3>Index</h3>
        <ul>
            <li><a href="<?php echo $this->url('units/unit')?>">Unit</a></li>
            <li><a href="<?php echo $this->url('units/building')?>">Building</a></li>
            <li><a href="<?php echo $this->url('units/resources')?>">Resource</a></li>
        </ul>
    </div>
    <div class="span4"><?php echo $this->units ?></div>
    <div class="span4"><?php echo $this->buildings ?></div>
    <div class="span4"><?php echo $this->resources ?></div>
</div>
