<?php
/**
 * @author Marco Bunge
 * @copyright 2012 Marco Bunge <efika@rubymatrix.de>
 */

?>
<div class="hero-unit">
    <h1><?=$info->offsetGet('name')?></h1>
    <h2>Units</h2>
    <a href="<?=$this->url('units')?>">Back</a>
</div>
<div class="row">
    <div class="span3">
        <span>Overview</span>
        <?php echo $this->linkList ?>
    </div>
    <div class="span9">
        <h4>Info</h4>
        <table class="table table-striped table-bordered">
            <?php foreach($info as $key => $value) : ?>
                <tr>
                    <th><?php echo $key?></th>
                    <td><?php echo $value?></td>
                </tr>
            <?php endforeach; ?>
        </table>
        <h4>Stats</h4>
        <table class="table table-striped table-bordered">
            <?php foreach($stats as $stat) : ?>
                <tr>
                    <th><?php echo $stat->offsetGet('name')?></th>
                    <td><?php echo $stat->offsetGet('value')?></td>
                    <td><?php echo $stat->offsetGet('type')?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>